# This rule is not used by the project simple-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the demo.demo.local.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: simple-operator
    app.kubernetes.io/managed-by: kustomize
  name: simple-editor-role
rules:
- apiGroups:
  - demo.demo.local
  resources:
  - simples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.demo.local
  resources:
  - simples/status
  verbs:
  - get
